apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-client-config
  namespace: ecommerce-dev
  labels:
    component: config
data:
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-discovery-service:8761/eureka/
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  SPRING_PROFILES_ACTIVE: kubernetes