apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
  namespace: ecommerce-dev
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://service-discovery-service:8761/eureka/"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"