apiVersion: v1
kind: ConfigMap
metadata:
  name: zipkin-config
  namespace: ecommerce-dev
data:
  JAVA_OPTS: "-Xmx384m -Xms256m -XX:MaxMetaspaceSize=128m"
  STORAGE_TYPE: "mem"
  ZIPKIN_LOG_LEVEL: "INFO"