apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: ecommerce-dev
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: ecommerce-dev
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 8700
    targetPort: 8700
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-service
  namespace: ecommerce-dev
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
  - port: 8400
    targetPort: 8400
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service-service
  namespace: ecommerce-dev
  labels:
    app: favourite-service
spec:
  selector:
    app: favourite-service
  ports:
  - port: 8800
    targetPort: 8800
    protocol: TCP
  namespace: ecommerce-dev
  labels:
    app: favourite-service
spec:
  selector:
    app: favourite-service
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce-dev
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 8300
    targetPort: 8300
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce-dev
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 8400
    targetPort: 8400
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: ecommerce-dev
  labels:
    app: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
  - port: 8600
    targetPort: 8600
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  namespace: ecommerce-dev
  labels:
    app: proxy-client
spec:
  selector:
    app: proxy-client
  ports:
  - port: 8900
    targetPort: 8900
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-service
  namespace: ecommerce-dev
  labels:
    app: cloud-config
spec:
  selector:
    app: cloud-config
  ports:
  - port: 9296
    targetPort: 9296
    protocol: TCP