apiVersion: v1
kind: Service
metadata:
  name: payment-service-service
  namespace: ecommerce-dev
  labels:
    app: payment-service
    component: microservice
spec:
  type: ClusterIP
  ports:
  - port: 8400
    targetPort: 8400
    protocol: TCP
    name: http
  selector:
    app: payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service-service
  namespace: ecommerce-dev
  labels:
    app: shipping-service
    component: microservice
spec:
  type: ClusterIP
  ports:
  - port: 8600
    targetPort: 8600
    protocol: TCP
    name: http
  selector:
    app: shipping-service
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service-service
  namespace: ecommerce-dev
  labels:
    app: favourite-service
    component: microservice
spec:
  type: ClusterIP
  ports:
  - port: 8800
    targetPort: 8800
    protocol: TCP
    name: http
  selector:
    app: favourite-service
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-client-service
  namespace: ecommerce-dev
  labels:
    app: proxy-client
    component: microservice
spec:
  type: ClusterIP
  ports:
  - port: 8900
    targetPort: 8900
    protocol: TCP
    name: http
  selector:
    app: proxy-client