apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  namespace: ecommerce-dev
  labels:
    app: zipkin
    component: tracing
spec:
  type: ClusterIP
  ports:
  - port: 9411
    targetPort: 9411
    protocol: TCP
    name: http
  selector:
    app: zipkin
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery-service
  namespace: ecommerce-dev
  labels:
    app: service-discovery
    component: discovery
spec:
  type: ClusterIP
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: http
  selector:
    app: service-discovery
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-service
  namespace: ecommerce-dev
  labels:
    app: cloud-config
    component: config
spec:
  type: ClusterIP
  ports:
  - port: 9296
    targetPort: 9296
    protocol: TCP
    name: http
  selector:
    app: cloud-config